management:
  endpoint:
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: 'my-example'
  main:
    banner-mode: 'off'
