logging:
  level:
    hm.binkley: 'INFO'
    root: 'WARN'

management:
  endpoint:
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: 'docker-java11'
  main:
    banner-mode: 'off'

---

spring:
  profiles: 'demo'
  application:
    name: 'bobs-yer-unkel'
